# Generated by Django 3.2.5 on 2021-07-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('passcode', models.CharField(max_length=10)),
                ('timezone_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('dosage', models.CharField(max_length=10)),
                ('form', models.CharField(choices=[('Cap', 'Cap')], max_length=10)),
                ('exact_pill_count', models.SmallIntegerField()),
                ('max_manual_doses', models.SmallIntegerField()),
                ('passcode_required', models.BooleanField()),
                ('expires', models.DateField()),
                ('slot', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
