# Generated by Django 3.2.5 on 2021-07-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0002_auto_20210708_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfig',
            name='timezone_name',
            field=models.CharField(max_length=25),
        ),
    ]
