# Generated by Django 3.2.5 on 2021-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_config', '0003_alter_deviceconfig_timezone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
